title : Supply Chain Analytics - Case Studies and Demos
author: Yossiri Adulyasak 
logo: 'sc_analytics_logo_small.png'

# Short description about the book
description: >-
  Case studie and demos of supply chain analytics.

only_build_toc_files        : true

parse:
   myst_url_schemes: [mailto, http, https]

execute:
  execute_notebooks           : cache
  allow_errors                : true
  
# HTML-specific settings
html:
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/acedesci/scanalytics_cases/tree/main/onlinebook
  path_to_book                : "book"

# binder:
#   binderhub_url               : "https://mybinder.org"
#   text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - docs/references.bib
latex:
  latex_engine                : xelatex
  latex_documents:
    targetname: scanalytics-cases.tex

# Citation format
sphinx:
  config:
    bibtex_reference_style: author_year
